<?php

declare(strict_types=1);

namespace Pollora\Portcullis\Domain\Model;

use Pollora\Portcullis\Domain\Exception\InvalidLoginSlugException;
use Stringable;

/**
 * The single URL path segment from which the WordPress login screen is served.
 *
 * This is a value object: once built it is guaranteed to be a non-reserved,
 * URL-safe, sufficiently long path segment. Every consumer in the package can
 * therefore treat it as trusted input and interpolate it into a URL without
 * further escaping.
 *
 * Only a *single* segment is accepted (no slashes). Nested paths would collide
 * with WordPress' own rewrite resolution and, more importantly, would make the
 * cookie path used by the password reset flow ambiguous — see the
 * `WpLoginScreenRenderer` adapter, which is where that cookie path is pinned.
 */
final class LoginSlug implements Stringable
{
    /**
     * Minimum length, in characters, of an acceptable slug.
     *
     * Short slugs are trivially enumerable and would give a false sense of
     * security, so they are rejected outright rather than merely discouraged.
     */
    public const MINIMUM_LENGTH = 5;

    /**
     * Path segments WordPress or Bedrock already own at the site root.
     *
     * Using any of these would either be shadowed by an existing endpoint or
     * would break the installation.
     *
     * @var list<string>
     */
    private const RESERVED = [
        'app',
        'index.php',
        'wp',
        'wp-activate.php',
        'wp-admin',
        'wp-comments-post.php',
        'wp-content',
        'wp-cron.php',
        'wp-includes',
        'wp-json',
        'wp-links-opml.php',
        'wp-login.php',
        'wp-mail.php',
        'wp-signup.php',
        'wp-trackback.php',
        'xmlrpc.php',
    ];

    /**
     * @param  string  $value  The normalised, validated slug.
     */
    private function __construct(private readonly string $value) {}

    /**
     * Builds a slug from a raw configuration value.
     *
     * The value is normalised first (surrounding whitespace and slashes are
     * dropped) so that `/connexion/`, ` connexion ` and `connexion` all yield
     * the same slug, then validated.
     *
     * @param  string  $value  Raw value coming from the environment or from a custom provider.
     *
     * @throws InvalidLoginSlugException When the value is empty, malformed, reserved or too short.
     */
    public static function fromString(string $value): self
    {
        $slug = trim($value);
        $slug = trim($slug, '/');
        $slug = trim($slug);

        if ($slug === '') {
            throw InvalidLoginSlugException::empty();
        }

        if (preg_match('/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?$/', $slug) !== 1) {
            throw InvalidLoginSlugException::malformed($slug);
        }

        if (in_array($slug, self::RESERVED, true)) {
            throw InvalidLoginSlugException::reserved($slug);
        }

        if (strlen($slug) < self::MINIMUM_LENGTH) {
            throw InvalidLoginSlugException::tooShort($slug, self::MINIMUM_LENGTH);
        }

        return new self($slug);
    }

    /**
     * The normalised slug, without any leading or trailing slash.
     */
    public function value(): string
    {
        return $this->value;
    }

    /**
     * The slug as a root-relative path, without a trailing slash.
     *
     * The absence of a trailing slash is deliberate and load-bearing: WordPress
     * scopes the `wp-resetpass-*` cookie on the current request path, and the
     * form generated by the reset screen posts to the URL built from this very
     * value. A trailing slash on one side and not on the other would silently
     * break the password reset flow.
     */
    public function toPath(): string
    {
        return '/'.$this->value;
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {
        return $this->value;
    }
}
